[project]
name = "lpp-collector"
version = "0.4.0"
description = ""
authors = [{ name = "f0reachARR", email = "f0reach@f0reach.me" }]
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "pytest>=8,<9",
    "whiptail-dialogs>=0.4.0,<0.5",
    "httpx>=0.20.0,<0.28.0",
    "pytest-timeout>=2,<3",
    "argcomplete>=3,<4",
]

[project.scripts]
lppconsent = "lpp_collector.consent:main"
lppsetup = "lpp_collector.consent:setup_main"
lpptest = "lpp_collector.runner:main_PYTHON_ARGCOMPLETE_OK"
lpprun = "lpp_collector.lpprun:main"
lppsubmit = "lpp_collector.submit:main"
lppc = "lpp_collector.lpprun:compile_main"
lppshell = "lpp_collector.shell:main"

[project.entry-points.pytest11]
lpp_collector = "lpp_collector"

[dependency-groups]
dev = ["pytest>=8,<9"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
